// System import
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.css';
import { ToastContainer } from 'react-toastify';

// Local Import
import "./globals.css";
import FavoriteProvider from "./context/FavoriteCocktailContext";
import NavBar from "./components/NavBar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="bg-gray-100 text-gray-900">
                <header className="bg-blue-500 text-white text-center p-4">
                  <h1 className="text-2xl font-bold">Cocktail App</h1>
                </header>
                <NavBar />
                <main className="container">
                    <FavoriteProvider>
                        {children}
                    </FavoriteProvider>
                    <ToastContainer />
                </main>
            </body>
        </html>
    );
}